apiVersion: v1
kind: Service
metadata:
  name: invoice-service
spec:
  selector:
    app: invoice
  ports:
  - protocol: TCP
    port: 3100
    targetPort: 3100
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoice
spec:
  selector:
    matchLabels:
      app: invoice
  replicas: 1
  template:
    metadata:
      labels:
        app: invoice
    spec:
      containers:
        - name: invoice
          image: 159091/invoice:1.0
          imagePullPolicy: Always
          command: ["sh", "-c", "node /app/main.js"]
          ports:
            - name: invoice-port
              containerPort: 3100
      dnsPolicy: ClusterFirstWithHostNet
      dnsConfig:
        nameservers:
          - 10.96.0.10
        options:
          - name: ndots
            value: "5"