apiVersion: skaffold/v2beta20
kind: Config
build:
  artifacts:
    - image: invoice
      context: .
      docker:
        dockerfile: Dockerfile
  local:
    push: false
deploy:
  kubectl:
    manifests:
      - deployment.yaml